services:
  postgres:
    image: postgres:16
    container_name: benchmark-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monolith
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_benchmark:/var/lib/postgresql/data

volumes:
  postgres_data_benchmark: